### ISSUE TITLE
Launch City 2.0

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#189]
@secretrobotron I'm reviving the Launch Checklist as we get closer.

### To-do

* [ ] Make AI less twitchy 
* [ ] Add seizure warning to the game
  * Winners don't use drugs
  * Flobotron Presents
* [ ] Resolve double-spin ball bug
  * Sometimes at the end of round...
* [ ] Look into x / d mode on the controller, one causes a JS crash @secretrobotron

### Sounds
* [ ] Adjust Sound levels so all the sounds are at the right level relative to each other
  * The 'bounce-disabled' is way quieter than the bounce-normal

### Other
* [ ] Make the DMG background cooler
  * What are DMG background dimensions? Seems like whatever we want
* [ ] Start an itchio page
* [ ] Set up itch.io
  * [ ] Set up github org
* [ ] Make a trailer
* [ ] Take amazing screenshots
* [ ] Do some performance testing

**Comment by secretrobotron** [comment]
We can probably poll `document.readyState` to figure out when to start animations after loading: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
