### ISSUE TITLE
Finish Battle Pong

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#26]
We are almost there with Battle Pong I think.

**To-Do**
* [x] Add a sound for scoring
* [x] Add a sound for winning
* [x] Add way to restart game after it is over
* [x] When a player scores, strobe the game border to that color (red or blue)
* [x] See about reducing friction against walls for the paddle, so that if you are up against it horizontally, you can move up and down easily.
* [x] Port latest controller code
* [x] ...?

![image](https://user-images.githubusercontent.com/25212/30748816-081ba564-9f77-11e7-9df6-fbf1ab6c4468.png)

**Comment by secretrobotron** [comment]
Can you port the controller stuff over here too? It would be great to add some functionality to let the user choose which setup they want. Then, we can let people use keyboard/phone/gamepad interchangeably.

**Comment by flukeout** [comment]
Yeah def, added it to the list above.

**Comment by flukeout** [comment]
Makin' some good progress here.

**Comment by flukeout** [comment]
Well, according to the checklist in this issue, we are DONE! Congrats @secretrobotron
