### ISSUE TITLE
Sound/music TODO

### ISSUE THREAD

**Issue by secretrobotron** [secretrobotron/games#89]
- [x] Fix timing on round-start sound
- [x] Figure out timing for different sounds+animations
- [ ] Try some small music loops to pick a sound direction
- [x] Sound ducking for important sounds
- [x] Low-pass filter if possible
- [ ] intro music
- [ ] "finish it" music
- [x] spin loop sounds
- [x] soundbank history for avoiding repeats

**Comment by secretrobotron** [comment]
Check out #90 for lowpass effect after bomb explosions

**Comment by secretrobotron** [comment]
@DevonBird I added music stuff to the spreadsheet

**Comment by secretrobotron** [comment]
From @DevonBird in #90:

> The Powershot sound in that build is definitely too loud XD I would turn it down quite a bit.

> PS. I added a new version of the Round_Start sound to the folder with no padding at the beginning

> Also... I just realized that there are 6 bones for the bones powerup instead of 5. I'll add a 6th Bones_Powerup_Disappear sound to the folder tomorrow.

**Comment by secretrobotron** [comment]
From https://docs.google.com/document/d/1rEufDPIAmAujDLds7kjYGR2s26pWNsyyLqoOKkUn2bk/edit?ts=5a6a9b38

> [Devon] - It would be great if we could control the volume reduction, attack time, sustain time, and release time for the ducking of the music for each event individually. 

* attack time (duration of fade to maximum volume reduction)
* sustain time (duration that the maximum volume reduction is held)
* release time (duration of fade back to normal volume)

**Comment by secretrobotron** [comment]
> Powerup_Spin_Spin sound, There are two sounds
* Start - Play this when the paddle starts spinning, then, if the paddle is still spinning, immediately transition to...
* Loop - and keep looping it.
* When the paddle stops spinning, Fade out the spin sound to 0 quickly (0.05 sec)

**Comment by flukeout** [comment]
Closing as I think we've moved past these considerations.
