### ISSUE TITLE
Launch City

### ISSUE THREAD

**Issue by flukeout** [secretrobotron/games#99]
@secretrobotron I'm reviving the Launch Checklist as we get closer.

### To-do

* [ ] Make AI less twitchy 
* [ ] Add seizure warning to the game
  * Winners don't use drugs
  * Flobotron Presents
* [ ] Resolve double-spin ball bug
  * Sometimes at the end of round...
* [ ] Look into x / d mode on the controller, one causes a JS crash @secretrobotron

### Sounds
* [ ] Adjust Sound levels so all the sounds are at the right level relative to each other
  * The 'bounce-disabled' is way quieter than the bounce-normal

**New sound requests**
* [ ] Mine disable
* [ ] Menu move effect
  * When the hand pointer moves around the menus, can be a little woosh?

### Other
* [ ] Make the DMG background cooler
  * What are DMG background dimensions? Seems like whatever we want
* [ ] Start an itchio page
* [ ] Set up itch.io
  * [ ] Set up github org
* [ ] Make a favicon
* [ ] Make a trailer
* [ ] Take amazing screenshots
* [ ] Do some performance testing

**Comment by secretrobotron** [comment]
- [ ] Get accounts on itchio and steam
- [ ] Yay or nay for AI (need to finish it)
- [ ] Yay or nay for network play (need to finish it)

**Comment by secretrobotron** [comment]
> Paddle sometimes spins twice as fast as it's supposed to when spinning

This bug is so annoying. It only happens when I'm way too tired to debug.

**Comment by secretrobotron** [comment]
>  Should we optimize the game for a certain aspect ratio?

Yeah, I think so. We should choose a wide ratio. It's not a game for phones or little screens. If you're playing it, you're playing it on a couch with a TV or at a monitor with some friends.

**Comment by flukeout** [comment]
Can you test out removing line 301 from effects.js

the `addtemporaryclassthing` see if that helps unstutter your performance on goals.

**Comment by secretrobotron** [comment]
@flukeout commenting out `addTemporaryClassName(this.bodyEl, "team-" + player + "-scored-flash", 500);` helps a little bit, but it's not the most consistent. Playing a little bit, I've noticed the bomb explosions really affect perf too though.

Also, I usually have the dev window open, which makes perf like 50% as good as normal. Need to try this stuff more deliberately later, I think.

**Comment by flukeout** [comment]
@secretrobotron sounds good, let's do a thorough pass later. Would be nice to graph out like the functions we're calling along with a little FPS chart.

**Comment by secretrobotron** [comment]
<img width="692" alt="screenshot 2018-03-27 22 00 49" src="https://user-images.githubusercontent.com/403231/38004465-66d55a34-320a-11e8-91ed-65f90a598605.png">

**Comment by secretrobotron** [comment]
names not already taken on itchio: bouke, bobuke, luob, onetwothreefourfive, yelb, bley, appmaker, zoup, fwoosh, whoosh, Powerup_Bones_Disapear_1

**Comment by ryanwarsaw** [comment]
I wonder what the options would look like if you had it combine them by flukeout first, then robot second since all of these are the opposite of that, you might get some funny ones =p

rukeout is my personal favorite

**Comment by secretrobotron** [comment]
Hahahah yeah @ryanwarsaw. I tried that too. I think this is not the best... word combo tool. hahaha

**Comment by secretrobotron** [comment]
<img width="714" alt="screenshot 2018-03-27 22 08 52" src="https://user-images.githubusercontent.com/403231/38004702-72e4d66e-320b-11e8-810c-b9a8c99b1d37.png">

**Comment by ryanwarsaw** [comment]
![screen shot 2018-03-27 at 9 10 23 pm](https://user-images.githubusercontent.com/6530909/38004747-529eca52-3203-11e8-8873-45a30786a437.png)

**Comment by secretrobotron** [comment]
You're right. "flobotron" is promising.

**Comment by ryanwarsaw** [comment]
it has a flubber (if you've ever seen that movie) kinda vibe to it

**Comment by secretrobotron** [comment]
# FLOBOS

**Comment by secretrobotron** [comment]
Real contender: http://gondola.itch.io/

**Comment by flukeout** [comment]
hah shit i came to post the app icon and just saw all these now haha, reviewing.

![app-icon](https://user-images.githubusercontent.com/25212/38147402-03d50aa2-3407-11e8-8e1e-8b8313df4c20.png)

**Comment by flukeout** [comment]
sweet @ryanwarsaw thanks for posting those. i'm digging `flobotron` `fluktron` `flobotron` etc etc.
`fotron` is sweet too

**Comment by secretrobotron** [comment]
@flukeout proposing a name change: "DEATHSTROID: Mobile Paddle Rocket *Destroyers*"

**Comment by secretrobotron** [comment]
>  Restore original analog spinning (not the current slow style)

Ok, I did this by removing the Y axis from the calculations. I think I was trying to conflate two methods of starting the spinning. Just using the X axis makes it really, really simple.

https://github.com/secretrobotron/games/pull/151

**Comment by secretrobotron** [comment]
> start button needs to trigger pause menu from game board

This what you had in mind? @flukeout https://github.com/secretrobotron/games/pull/152

**Comment by secretrobotron** [comment]
@flukeout a couple more things to note from a quick playtest:

- [x] HOLY MOLY THE SOUNDS AND MUSIC ARE GREAT NOW THANKS @DevonBird 
- [ ] There is a long pause between rounds. Is it longer than before? It feels like the game is frozen. Might be just my machine acting up?
- [ ] The AI seems to be more impossible than usual now. I think I'm going to have to slow it down.

**Comment by flukeout** [comment]
Oh yeah, ill add a bullet point to fix the round delay. It's because I was delaying it longer for the animation where the board flies in but now every single round is delayed as a result.

**Comment by secretrobotron** [comment]
@flukeout can you drop in a huge version of the app icon? It's got to be at least 512x512.

**Comment by secretrobotron** [comment]
# Music
* Splash screen has chill version of regular music, so you feel good using the menu
  * If you are on the splash screen, and you press Guide, the music shouldn't change
  * But, if you are in game and press pause, you should just hear the first layer of music
    * When you unpause, eveyrthing comes back up
* When you start the game
  * Crossfade from splash screen music to intro music
  * Before end of reverb tail of intro music, start gameplay music loop
  * For every gameplay pseudo-loop, start loop again before end of reverb tail

**Comment by secretrobotron** [comment]
@DevonBird ^^

**Comment by secretrobotron** [comment]
@flukeout I'll take a crack at this music stuff this weekend. It sounds soooooo good.

Also, I found a couple more cursor bugs: https://github.com/secretrobotron/games/issues/162. Happy to tinker with those too if you're sick of cursor algorithms now hahah.

**Comment by secretrobotron** [comment]
@flukeout @DevonBird I landed all the music stuff I've been working on. Let me know how it sounds in your ears. 😄

**Comment by secretrobotron** [comment]
I just realized that the music looping is broken on the menu & rules page though. I marked it down here to fix. Will fix ASAP.
